Change setup program to accept multiple commands

diff --git a/libinput-gestures-setup b/libinput-gestures-setup
--- a/libinput-gestures-setup
+++ b/libinput-gestures-setup
@@ -21,32 +21,41 @@ CHECKSECS=6
 usage() {
     echo "Usage:"
     echo "As root: sudo $PROG install|uninstall"
-    echo "As user: $PROG service|desktop|"
-    echo "         start|stop|restart|autostart|autostop|status"
+    echo "  -d <dir> (option sets DESTDIR for install/uninstall)"
     echo
-    echo "-d <dir> (option sets DESTDIR for install/uninstall)"
-    echo "-r (force allow root to perform user commands. PLEASE AVOID USING THIS!)"
+    echo "As user: $PROG command [command ..]"
+    echo "  where command is any of:"
+    echo "  start|stop|restart|autostart|autostop|status"
+    echo
     exit 1
 }
 
 # Process command line options
 DESTDIR=""
-FORCEROOT=0
-while getopts d:r c; do
+while getopts d: c; do
     case $c in
     d) DESTDIR="$OPTARG";;
-    r) FORCEROOT=1;;
     \?) usage;;
     esac
 done
 
 shift $((OPTIND - 1))
 
-if [[ $# -ne 1 ]]; then
-    usage
+# Test if systemd is installed
+if type systemctl &>/dev/null; then
+    HAS_SYSD=1
+else
+    HAS_SYSD=0
 fi
 
-cmd="$1"
+# Test if given systemd property is set for service
+sysd_prop() {
+    if systemctl --user show -p $1 $NAME.service | grep -q "=$2$"; then
+	echo 1
+    else
+	echo 0
+    fi
+}
 
 # Launch given desktop app. First work out most suitable launcher.
 # Pretty crude at present but should work for at least GNOME and KDE.
@@ -112,13 +121,19 @@ de_auto_start() {
 # Action given user command
 user_action() {
     local cmd="$1"
-    local has_sysd="$2"
-    local svc_enabled="$3"
-    local svc_running="$4"
     local pidfile=/tmp/$NAME-$USER.pid
 
+    # Test if systemd is enabled/running
+    if [[ $HAS_SYSD -eq 1 ]]; then
+	svc_enabled=$(sysd_prop UnitFileState enabled)
+	svc_running=$(sysd_prop SubState running)
+    else
+	svc_enabled=0
+	svc_running=0
+    fi
+
     if [[ $cmd == service ]]; then
-	if [[ $has_sysd -eq 0 ]]; then
+	if [[ $HAS_SYSD -eq 0 ]]; then
 	    echo "Systemd not available, can not run as service."
 	    exit 1
 	fi
@@ -127,18 +142,18 @@ user_action() {
 	rm -fv $AUTDIR/$NAME.desktop
     elif [[ $cmd == desktop ]]; then
 	rm -f $SVCFLG
-	if [[ $has_sysd -eq 1 ]]; then
+	if [[ $HAS_SYSD -eq 1 ]]; then
 	    systemctl --user disable $NAME.service &>/dev/null
 	fi
     elif [[ $cmd == start ]]; then
-	STARTBY=""
+	STARTAS=""
 	if [[ -f $SVCFLG ]]; then
-	    if [[ $has_sysd -eq 0 ]]; then
+	    if [[ $HAS_SYSD -eq 0 ]]; then
 		echo "Systemd is not installed."
 		exit 1
 	    fi
 	    if systemctl --user start $NAME.service; then
-		STARTBY="as a user service"
+		STARTAS="user service"
 	    fi
 	else
 	    if [[ ! -f $APPDIR/$NAME.desktop ]]; then
@@ -146,14 +161,14 @@ user_action() {
 		exit 1
 	    fi
 	    if de_start "$NAME"; then
-		STARTBY="by desktop"
+		STARTAS="desktop application"
 	    fi
 	fi
 
-	# Wait some time to start ..
-	if [[ -n $STARTBY ]]; then
+	if [[ -n $STARTAS ]]; then
+	    # Wait some time to start ..
 	    done=0
-	    for c in $(seq $CHECKSECS); do
+	    for _ in $(seq $CHECKSECS); do
 		sleep 1
 		if ps "$(head -1 $pidfile 2>/dev/null)" &>/dev/null; then
 		    done=1
@@ -162,16 +177,16 @@ user_action() {
 	    done
 
 	    if [[ $done -eq 1 ]]; then
-		echo "$NAME started $STARTBY".
+		echo "$NAME started as a $STARTAS".
 	    else
-		echo "$NAME failed to start $STARTBY". >&2
+		echo "$NAME failed to start as a $STARTAS". >&2
 	    fi
 	fi
     elif [[ $cmd == stop ]]; then
-	STARTBY=""
+	STARTAS=""
 	if [[ $svc_running -eq 1 ]]; then
 	    systemctl --user stop $NAME.service
-	    STARTBY="user service"
+	    STARTAS="user service"
 	else
 	    if [[ -f $pidfile ]]; then
 		local killed=0
@@ -181,15 +196,15 @@ user_action() {
 		    fi
 		done <$pidfile
 		if [[ $killed -ne 0 ]]; then
-		    STARTBY="for desktop"
+		    STARTAS="desktop application"
 		fi
 	    fi
 	fi
 
-	if [[ -n $STARTBY ]]; then
+	if [[ -n $STARTAS ]]; then
 	    # Wait some time to stop ..
 	    done=0
-	    for c in $(seq $CHECKSECS); do
+	    for _ in $(seq $CHECKSECS); do
 		sleep 1
 		if ! ps "$(head -1 $pidfile 2>/dev/null)" &>/dev/null; then
 		    done=1
@@ -198,14 +213,14 @@ user_action() {
 	    done
 
 	    if [[ $done -eq 1 ]]; then
-		echo "$NAME stopped $STARTBY".
+		echo "$NAME stopped $STARTAS".
 	    else
-		echo "$NAME failed to stop $STARTBY". >&2
+		echo "$NAME failed to stop $STARTAS". >&2
 	    fi
 	fi
     elif [[ $cmd == autostart ]]; then
 	if [[ -f $SVCFLG ]]; then
-	    if [[ $has_sysd -eq 0 ]]; then
+	    if [[ $HAS_SYSD -eq 0 ]]; then
 		echo "Systemd is not installed."
 		exit 1
 	    fi
@@ -218,12 +233,12 @@ user_action() {
 		echo "$NAME is not installed."
 		exit 1
 	    fi
-	    if [[ $has_sysd -eq 1 ]]; then
+	    if [[ $HAS_SYSD -eq 1 ]]; then
 		systemctl --user disable $NAME.service &>/dev/null
 	    fi
 	fi
     elif [[ $cmd == autostop ]]; then
-	if [[ $has_sysd -eq 1 ]]; then
+	if [[ $HAS_SYSD -eq 1 ]]; then
 	    systemctl --user disable $NAME.service &>/dev/null
 	fi
 	rm -fv $AUTDIR/$NAME.desktop
@@ -265,24 +280,20 @@ user_action() {
 	    echo "$NAME is using default configuration."
 	fi
     else
-	usage
+	echo "ERROR: \"$cmd\" is not a valid user command" >&2
     fi
 }
 
-# Test if given systemd property is set for service
-sysd_prop() {
-    if systemctl --user show -p $1 $NAME.service | grep -q "=$2$"; then
-	echo 1
-    else
-	echo 0
-    fi
-}
-
+cmd="$1"
 if [[ $cmd == install || $cmd == uninstall ]]; then
     DESTDIR="${DESTDIR%%+(/)}"
     if [[ -z $DESTDIR && $(id -un) != root ]]; then
 	echo "Install or uninstall must be run as sudo/root."
 	exit 1
+    fi
+
+    if [[ $# -ne 1 ]]; then
+	usage
     fi
 
     # Remove any old files from earlier versions of program
@@ -316,7 +327,7 @@ if [[ $cmd == install || $cmd == uninstall ]]; then
 	fi
     fi
 else
-    if [[ $(id -un) == root && $FORCEROOT == 0 ]]; then
+    if [[ $(id -un) == root ]]; then
 	echo "Non-installation commands must be run as your own user."
 	exit 1
     fi
@@ -338,23 +349,15 @@ else
 	de_auto_start
     fi
 
-    # Test if systemd is installed
-    if type systemctl &>/dev/null; then
-	has_sysd=1
-	svc_enabled=$(sysd_prop UnitFileState enabled)
-	svc_running=$(sysd_prop SubState running)
-    else
-	has_sysd=0
-	svc_enabled=0
-	svc_running=0
-    fi
+    # Execute each command given on command line ..
+    for cmd in "$@"; do
+	if [[ $cmd == restart ]]; then
+	    user_action "stop"
+	    cmd=start
+	fi
 
-    if [[ $cmd == restart ]]; then
-	user_action "stop" $has_sysd $svc_enabled $svc_running
-	cmd=start
-    fi
-
-    user_action $cmd $has_sysd $svc_enabled $svc_running
+	user_action "$cmd"
+    done
 fi
 
 exit 0
